hints = {
    'style': [
        "surrealism",
        "symbolism",
        "psychedelic art",
        ["impressionism",
         "neo-expressionist"],
        "cyberpunk",
        ["art photography",
         "artistic photorealism"],
        ["professional photo",
         "iphone photo"],
        "poster art",
        "edgy street art",
        "afrofuturism style",
        "in the style of chinapunk",
        "urbanpunk",
        "painterly style",
    ],
    'quality': [
        ["ultra resolution",
         "ultra high res"
         "highest resolution"],
        "hyperrealistic",
        "perfectly balanced",
        "score_9",
        "35mm photography",
        ["8k RAW photo",
         "8k uhd",
         "detailed cg unity 8k wallpaper"],
        "masterpiece",
        ["trending on ArtStation",
         "trending on CGSociety"],
        ["super quality",
         "best quality"],
        "highly detailed" # could be not "quality"
    ],
    'shooting': [
        "double exposure",
        "extremely sharp focus",
        "large depth of field",
        "deep depth of field",
        ["artistic blur", "bokeh"],
        "soft focus"
    ],
    "effects": [
        "strong environmental light",
        "cinema lighting",
        "reflections",
        "sheen",
        "glowing"
    ],
    'style_modifiers': [
        "geometric patterns",
        ["fusion of art styles",
         "concept art",
         "fine art"],
        "grafitti",
        "splash",
        "modern ink",
        "multi-layered collages",
        "iconic album covers",
        "fragmented icons"
    ],
    'vibe': [
        "energy-filled illustration",
        "intricate",
        "vibrant",
        "aesthetic"
    ],
    'colors': [
        "pastel colors",
        "bioluminescens color",
        "vibrant palette",
        "colorful",
        "dreamlike colors",
        "neon lights",
        "black and white",
        "monochrome",
    ],
    'author_style': [
        "Jean-Baptiste Monge style",
        "styled in Art Nouveau",
        "painting by Ed Blinkey",
        "by Atey Ghailan",
        "by Jeremy Mann",
        "by Greg Manchess",
        "by Antonio Moro",
        "painting art by greg rutkowski",
        "in the style of kandinsky",
        "in the style of guillem h. pongiluppi",
        "by abigail larson",
        "by john sloane",
        "in the style of John Berkey",
        "by Russ Mills",
        "by george callaghan",
        "by Ian Miller",
        "by luke fildes"
    ]
}
