hints = {
    'style': [
        "surrealism",
        ["symbolism", "cubism"],
        "psychedelic art",
        ["impressionism",
         "expressionism",
         "neo-expressionist"],
        "neoclassicism",
        ["cyberpunk",
         "urbanpunk",
         "cyberpunk mood",
         "cyberpunk rave"],
        ["snthwve style",
         "nvinkpunk style",
         "ink punk style"],
        ["art photography",
         "artistic photorealism"],
        ["professional photo",
         "iphone photo"],
        "poster art",
        "edgy street art",
        ["afrofuturism style",
         "in the style of chinapunk"],
        ["sci-fi concept art",
         "scifi style",
         "futuristic"],
        "painterly style",
        "pixar style",
        "quilling",
        ["pencil sketch",
         "pencil painting"],
        "watercolor painting"
    ],
    'quality': [
        ["ultra resolution",
         "ultra high res",
         "highest resolution",
         "absurdres"],
        ["hyperrealistic",
         "detailed hyperrealism"],
        "perfectly balanced",
        "score_9",
        "35mm photography",
        ["8k RAW photo",
         "8k uhd",
         "cg unity 8k wallpaper",
         "16k hdri", "32k UHD"],
        ["masterpiece", "famous artwork"],
        ["trending on ArtStation",
         "trending on CGSociety"],
        ["super quality",
         "best quality",
         "extreme quality",
         "top quality"],
        ["highly detailed",
         "high detail",
         "ultra-detailed"]  # could be not "quality"
    ],
    'shooting': [
        "double exposure",
        "extremely sharp focus",
        "large depth of field",
        "deep depth of field",
        ["artistic blur", "bokeh"],
        "soft focus",
        "cinematic shot",
        ["35mm photo",
         "50mm photo"],
        "dynamic angle",
        "film grain"
    ],
    'effects': [
        "strong environmental light",
        ["cinema lighting", "cinematic light"],
        "haze lighting",
        "reflections",
        "light leaks",
        "detailed shading",
        "soft shadows",
        "sheen",
        "glowing",
        "dynamic motion"
    ],
    'style_modifiers': [
        "geometric patterns",
        ["fusion of art styles",
         "concept art",
         "fine art"],
        "grafitti",
        "splash",
        "modern ink",
        ["multi-layered collages",
         "abstract multilayer texture"],
        "iconic album covers",
        "fragmented icons",
        "stylized photo",
        "cinematic illustration",
        "dripping paint",
        "splatter art",
        "fractal art",
        "oil on canvas",
        ["digital painting", "digital dreamscape"],
        "holographic style"
    ],
    'vibe': [
        "energy-filled illustration",
        "intricate",
        "vibrant",
        "stunning",
        "aesthetic",
        "sensual",
        "radiant vibe"
    ],
    'colors': [
        "pastel colors",
        "bioluminescens color",
        "vibrant palette",
        "colorful",
        "dreamlike colors",
        "neon lights",
        "black and white",
        "monochrome",
        "unusual colors",
        "complementary colors",
        "flowing colors",
        "dark",
        "bright",
        "24bit colors"
    ],
    'author_style': [
        "Jean-Baptiste Monge style",
        "styled in Art Nouveau",
        "painting by Ed Blinkey",
        "by Atey Ghailan",
        "by Jeremy Mann",
        "by Greg Manchess",
        "by Antonio Moro",
        "painting art by greg rutkowski",
        "in the style of kandinsky",
        "in the style of guillem h. pongiluppi",
        "by Abigail Larson",
        "by John Sloane",
        "in the style of John Berkey",
        "by Russ Mills",
        "by George Callaghan",
        "by Ian Miller",
        "by Luke Fildes",
        "inspired by Chris Achilleos",
        "by James Jean",
        "style of Wayne Barlowe",
        "style of Tyler Edlin",
        "style of Carne Griffiths",
        "by Anna Razumovskaya",
        "by Minjae Lee",
        "by Ana Paula Hoppe",
        "by ilya kuvshinov",
        "by Jamie Hewlett",
        "by Peter Mohrbacher",
        "by Martine Johanna"
    ]
}
